### ISSUE TITLE
Support for ramda 0.24.0

### ISSUE THREAD

**Issue by char0n** [char0n/ramda-adjunct#86]

**Comment by char0n** [comment]
Constrain peerDep from >= 19 <= 0.24.0

**Comment by char0n** [comment]
High priority.

**Comment by char0n** [comment]
0.24.1

**Comment by rockymadden** [comment]
When running against version `0.24.1`, I was getting: ```/Users/rockymadden/Documents/bodenstein/node_modules/ramda/src/internal/_dispatchable.js:29
        if (typeof obj[methodNames[idx]] === 'function') {
                      ^

TypeError: Cannot read property 'fantasy-land/map' of undefined
    at /Users/rockymadden/Documents/bodenstein/node_modules/ramda/src/internal/_dispatchable.js:29:23
    at f2 (/Users/rockymadden/Documents/bodenstein/node_modules/ramda/src/internal/_curry2.js:25:16)
    at /Users/rockymadden/Documents/bodenstein/node_modules/ramda/src/liftN.js:28:24
    at f1 (/Users/rockymadden/Documents/bodenstein/node_modules/ramda/src/internal/_curry1.js:17:17)
    at Object.<anonymous> (/Users/rockymadden/Documents/bodenstein/node_modules/ramda-adjunct/lib/isNotArrayLike.js:26:44)
    at Module._compile (module.js:569:30)
    at Module._extensions..js (module.js:580:10)
    at extensions.(anonymous function) (/Users/rockymadden/Documents/bodenstein/node_modules/require-precompiled/index.js:16:3)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/rockymadden/Documents/bodenstein/node_modules/ava/lib/process-adapter.js:100:4)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/rockymadden/Documents/bodenstein/node_modules/ramda-adjunct/lib/index.js:123:23)
    at Module._compile (module.js:569:30)
    at Module._extensions..js (module.js:580:10)
    at extensions.(anonymous function) (/Users/rockymadden/Documents/bodenstein/node_modules/require-precompiled/index.js:16:3)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/rockymadden/Documents/bodenstein/node_modules/ava/lib/process-adapter.js:100:4)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/rockymadden/Documents/bodenstein/test/lib/core.js:5:46)
    at Module._compile (module.js:569:30)
    at extensions.(anonymous function) (/Users/rockymadden/Documents/bodenstein/node_modules/require-precompiled/index.js:13:11)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/rockymadden/Documents/bodenstein/node_modules/ava/lib/process-adapter.js:100:4)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/rockymadden/Documents/bodenstein/node_modules/ava/lib/test-worker.js:49:1)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3```

**Comment by char0n** [comment]
@rockymadden working on it.

**Comment by char0n** [comment]
@rockymadden released v1.9.0 that adds support for 0.24.0 and 0.24.1 - https://www.npmjs.com/package/ramda-adjunct

**Comment by rockymadden** [comment]
Thank you *very* much, @char0n!
