### ISSUE TITLE
Cata doesn't work with folktale Result type

### ISSUE THREAD

**Issue by nsinghal90** [char0n/ramda-adjunct#922]
The cata function throws up an error with folktale 2.3.2 Result.

<pre><code>import * as R from 'ramda';
import * as RA from 'ramda-adjunct';
import Result from 'folktale/result';

const leftF = R.pipe(
  R.tap(console.log),
);
console.log(RA.cata(leftF, R.identity)(Result.Error('aaa')));</code></pre>

> /home/runner/node_modules/ramda-adjunct/lib/cata.js:63
  return catamorphicObj.either(leftFn, rightFn);
                        ^
>> TypeError: catamorphicObj.either is not a function
    at /home/runner/node_modules/ramda-adjunct/lib/cata.js:63:25
    at /home/runner/node_modules/ramda/src/internal/_curryN.js:37:27
    at /home/runner/node_modules/ramda/src/internal/_arity.js:10:19
    at Object.<anonymous> (/home/runner/src/test.js:37:13)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Module._compile (/home/runner/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Object.newLoader [as .js] (/home/runner/node_modules/pirates/lib/index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)

**Comment by char0n** [comment]
True. We’ll use ‘matchWith’ to support Result, Validation and Maybe types from folktake

**Comment by char0n** [comment]
Attached is pull request which adds support for monet.js, folktale and ramda-fantasy. Supported catamorphic types are: Maybe, Either, Result, Validation
